# HLint configuration file
# https://github.com/ndmitchell/hlint

- ignore: {name: "Use camelCase"}
- ignore: {name: "Redundant bracket"}
- ignore: {name: "Use newtype instead of data"}
- ignore: {name: "Monoid law, left identity", within: [prop_monoidLeftIdentity]}
- ignore: {name: "Monoid law, right identity", within: [prop_monoidRightIdentity]}

# Custom rules for the project
- warn: {lhs: "a == True", rhs: "a"}
- warn: {lhs: "a == False", rhs: "not a"}