# HLint configuration file
# https://github.com/ndmitchell/hlint

- ignore: {name: "Use camelCase"}
- ignore: {name: "Redundant bracket"}
- ignore: {name: "Use newtype instead of data"}

# Custom rules for the project
- warn: {lhs: "a == True", rhs: "a"}
- warn: {lhs: "a == False", rhs: "not a"}